IMAGE_ICONS = "icons"
IMAGE_BANNERS = "banners"

KEY_ICONS = IMAGE_ICONS
KEY_ICONS_DATES = "iconsDates"
KEY_BANNERS = IMAGE_BANNERS
KEY_BANNERS_DATES = "bannersDates"

BASE_GUILD = {KEY_ICONS: {}, KEY_ICONS_DATES: {}, KEY_BANNERS: {}, KEY_BANNERS_DATES: {}}
